### Variables
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc3Mzg0MzMxMCwiZXhwIjoxNzczODQ0MjEwfQ.5HDBemiMIJ7m9-L5rjAkSCI2ByQH2xdlMYRtEY4p6HM
@refreshToken = e665f22faaae3e075f2a02e7913a1c0d620e5ed9199767929e32adf7a10ceabc1d095004cda1481d6aae8e4d9dd3bf269a2c43c419d793c4cf7bc58111e46073

### AUTH

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "first_name": "John",
  "last_name": "Doe"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### USERS

### Get all users
GET {{baseUrl}}/users

### Get user by id
GET {{baseUrl}}/users/2

### Update user
PATCH {{baseUrl}}/users/2
Content-Type: application/json

{
  "first_name": "Jane"
}

### Delete user
DELETE {{baseUrl}}/users/2